### PR TITLE
Moar Keywords!

### PR DESCRIPTION
**Pull request by zeke**
This is an attempt to add a bunch of new keywords to emojilib. This PR just contains a diff to `emojis.json`. The code that produces the change doesn't really need to stick around in the codebase so it's living in [another branch](https://github.com/zeke/emojilib/blob/c79348e8a40bd85a9acfff2774843c3799925075/extend.js).

Here's the process:

1. Combine object key (`car`) and existing keywords (`red`, `transportation`, `vehicle`) into a single array.
1. For each term in the array, look up synonyms using the [OpenOffice thesaurus](https://github.com/daizoru/node-thesaurus) node module.
1. Add new terms to the keywords away, if:
  - word is not already a keyword
  - word is [somewhat common](https://www.npmjs.com/package/subtlex-word-frequencies)
  - word is not [profane](https://github.com/raymondjavaxx/swearjar-node)
  - word is not in my hand-compiled [list of stopwords](https://github.com/zeke/emojilib/blob/1eb5d7309e199fadb8843e4ba918f6c675d5d439/stopwords.txt)

Result: 

```
npm i -g json && cat emojis.json | json car | json keywords
```

Before:

```json
[
  "red",
  "transportation",
  "vehicle"
]
```

After:

```json
[
  "red",
  "transportation",
  "vehicle",
  "auto",
  "automobile",
  "machine",
  "compartment",
  "carmine",
  "cherry",
  "crimson",
  "ruby",
  "scarlet",
  "transit",
  "transfer",
  "fare",
  "shipping",
  "transport"
]
```

There are some results that are a little odd, so the stopwords list might need to be expanded, but in general I think this is pretty useful. As a [mojibar](https://github.com/muan/mojibar) or [emoji.muan.co](http://emoji.muan.co/) user, my chances of finding the right emoji are improved by these additional words, even if I end up seeing some extra unexpected emojis that match my query.

### CODE REVIEW

**Comment by zeke** [comment]
Oops test are failing. Will fix.

**Comment by muan** [comment]
I think the new set of keywords are really too broad, in the example there are only 3 I think are worth keeping. Imo the stopword list needs to expand by a lot to keep the keyword data useful but not bloated... I want to use Google's Vision API for this... 💭

**Comment by zeke** [comment]
> I want to use Google's Vision API

Sounds interesting. I also just discovered https://www.powerthesaurus.org which is crowdsourced. I'm not sure they have an API but it could be worth a try. https://www.powerthesaurus.org/car is definitely better than the Open Office results above...

I will close this out for now and perhaps make another pass at it later.

**Comment by zeke** [comment]
@muan I ended up revisiting this project using data from powerthesaurus.org. Here are the modules that came out of the effort:

https://github.com/zeke/powerthesaurus-api
https://github.com/ummoji/emoji-synonyms

And here's the larger work in progress, inspired heavily by mojibar!

https://github.com/ummoji

**Pull request closed without merging**
