### PR TITLE
Update emojis.json 

### PR DESCRIPTION
**Pull request by iamdharmveer**
New Keyword were added in emojis.json file so it's strength will improve .
eg.In "smiley"  tag   added keyword ->"funny" like more etc.

### CODE REVIEW

**Comment by muan** [comment]
Hi, please fix the conflicts. And once you do that the test will fail due to the formatting, please keep the keyword array on one line.

**Comment by iamdharmveer** [comment]
Check it again maybe now it's right 👍

**Comment by muan** [comment]
Looks like there are still conflicts. 🤓

**Comment by muan** [comment]
Thanks!

**Pull request merged**
