### PR TITLE
Added gorilla

### PR DESCRIPTION
**Pull request by Fastidious**
Added the "gorilla" emoji.

### CODE REVIEW

**Comment by Fastidious** [comment]
Not sure how to fix the issue, so it will pass Travis, anyone?

**Comment by fathertime** [comment]
Travis is failing in test.js. It looks like the emoji count is hard-coded and needs to be updated when you add emoji(s).

Here are the 2 lines to update:
https://github.com/muan/emojilib/blob/master/test.js#L39
https://github.com/muan/emojilib/blob/master/test.js#L63

**Comment by Fastidious** [comment]
@fathertime it seems there are other PRs pushed before that have not been merged. That is making matters worse. :-(

**Comment by muan** [comment]
Thanks!

**Pull request merged**
