### PR TITLE
Unicode 8 Nature

### PR DESCRIPTION
**Pull request by wbinnssmith**
Branched from #25.

I've still yet to figure out the ordering too :stuck_out_tongue: 

Also, iOS has renamed "Nature" to "Animals and Nature". Should we follow suit?

### CODE REVIEW

**Comment by muan** [comment]
> Also, iOS has renamed "Nature" to "Animals and Nature". Should we follow suit?

:+1: I think so.

**Comment by wbinnssmith** [comment]
Just pushed up my best-effort at reordering the nature category, which is now called `animalsandnature`. What do you think of underscore-casing categories as well => `animals_and_nature`?

**Comment by muan** [comment]
> What do you think of underscore-casing categories as well => `animals_and_nature`?

:+1: for underscore-casing them. wouldn't make sense if `sand` matches in `animalsandnature`.

**Comment by yoshokatana** [comment]
:+1: for snake_case, since it's used for the emoji keys as well (and also some keywords)

**Comment by wbinnssmith** [comment]
awesome. Just did this. I left the other categories alone for now (though they should also be snakecased soon) to prevent conflicts with @yoshokatana and other's work.

**Comment by wbinnssmith** [comment]
hmm, not sure what's up with Travis here. Everything passes locally..

**Comment by muan** [comment]
@wbinnssmith I added a test on master, which checks if the number of `keys` matches number of emoji.

**Comment by wbinnssmith** [comment]
Ah yeah. Forgot that Travis runs the merge of the base and target branches.
I'll fix this up.

**Comment by yoshokatana** [comment]
Yup! I added a comment to that test to update the number when more emoji were added, but perhaps it should be in the readme somewhere :p

**Comment by wbinnssmith** [comment]
just fixed it up!

**Comment by muan** [comment]
Hi! Is this merge-able now? Just checking. 🔍 
I haven't upgraded to El Capitan. 😬

**Comment by wbinnssmith** [comment]
Yep! As long as there aren't any conflicts (which there are bound to be
with the other PRs, happy to resolve if those are merged first)

**Comment by muan** [comment]
Sorry it took so long. Just merged this :sparkles:!

**Pull request merged**
